### ISSUE TITLE
8knobs_mono no arduino sketch

### ISSUE THREAD

**Issue by pirvcb** [tomcombriat/TES_8-knobs-synth#4]
Hi Thomas,
inside the 8knobs_mono Synth, the Arduino    .ino sketch is not present.
Could you publish it?
Thanks

**Comment by tomcombriat** [comment]
Hi,
This is the hardware folder. At the beginning I was planning to make several config, but it did not happen and moved to the 10k instead. All sketches are in the [main folder](https://github.com/tomcombriat/TES_8-knobs-synth), so for instance the [standard XORAND](https://github.com/tomcombriat/TES_8-knobs-synth/tree/master/XORAND_poly).

Note: mono in `8knobs_mono` refers to mono vs stereo, whereas poly in `XORAND_poly` refers to polyphonic versus monophonic.
